# For more support on how to run this workflow, please visit https://github.com/marketplace/actions/deploy-to-cloud-run

name: Build and Deploy to Cloud Run

on:
  push:
    branches: [""]

env:
  PROJECT_ID:
  SERVICE:
  REGION: europe-west1
  WIF_PROVIDER:
  SERVICE_ACCOUNT:
  REGISTRY:

jobs:
  deploy:
    permissions:
      contents: "read"
      id-token: "write"

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: DataFleetFrontend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: "google-github-actions/auth@v2"
        with:
          project_id: "${{ env.PROJECT_ID }}"
          workload_identity_provider: "${{env.WIF_PROVIDER}}"
          token_format: "access_token"
          service_account: "${{env.SERVICE_ACCOUNT}}"

      - name: Docker Auth
        id: docker-auth
        uses: "docker/login-action@v3"
        with:
          username: "oauth2accesstoken"
          password: "${{ steps.auth.outputs.access_token }}"
          registry: "${{ env.REGISTRY }}"

      - name: Build and Push Container
        run: |-
          docker build -t "${{ env.REGISTRY }}/${{ env.SERVICE }}:${{ github.sha }}" ./
          docker push "${{ env.REGISTRY }}/${{ env.SERVICE }}:${{ github.sha }}"

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          image: ${{ env.REGISTRY }}/${{ env.SERVICE }}:${{ github.sha }}

        #  gcloud run deploy s01-frontend --image europe-west1-docker.pkg.dev/staging1-svc-9ty5/staging/s01-frontend:dbdc08e731d32d49d3234c4833457c293ce5529b --update-labels ^,^managed-by=github-actions,commit-sha=dbdc08e731d32d49d3234c4833457c293ce5529b --format json --region europe-west1

      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
